In [ ]:
#!pip install numpy

In [5]:
import numpy as np
# Importing this because we will use it a lot
from numpy import array
from numpy import *

In [2]:
data = [11, 22, 33, 44, 55]

In [4]:
print(data)

[11, 22, 33, 44, 55]


In [6]:
type(data)

list

In [7]:
data = array(data)

In [8]:
print(data)

[11 22 33 44 55]


In [9]:
type(data)

numpy.ndarray

In [10]:
data = [[11, 22], [33, 44], [55, 66]]

In [11]:
data = [[11, 22],
        [33, 44],
        [55, 66]]

In [12]:
data

[[11, 22], [33, 44], [55, 66]]

In [13]:
data[1][1]

44

In [14]:
data[1]

[33, 44]

In [15]:
data = array(data)

In [16]:
data

array([[11, 22],
       [33, 44],
       [55, 66]])

In [17]:
type(data)

numpy.ndarray

In [20]:
# (1, 1) called a 'tuple'
data[(1, 1)]

44

In [21]:
data[1][1]

44

In [22]:
data[1]

array([33, 44])

In [23]:
data

array([[11, 22],
       [33, 44],
       [55, 66]])

In [24]:
data[0]

array([11, 22])

In [132]:
#data[4]

In [133]:
#data[(0,4)]

In [28]:
data[-1]

array([55, 66])

In [29]:
data

array([[11, 22],
       [33, 44],
       [55, 66]])

In [30]:
data[-2]

array([33, 44])

In [31]:
data[(-1, -1)]

66

Practice!
Access 44 two different ways:

With two positive integers

With two negative integers

In [32]:
data

array([[11, 22],
       [33, 44],
       [55, 66]])

In [33]:
data[(1, 1)]

44

In [34]:
data[(-2, -1)]

44

In [35]:
data[(-2, 1)]

44

In [36]:
# if had 6D data
# data[(-1, -1, -1, -1, -1, -1)]

data[from:to]

In [37]:
data = array([11, 22, 33, 44, 55])

In [38]:
data[:]

array([11, 22, 33, 44, 55])

In [39]:
# 
data[1:-1]

array([22, 33, 44])

In [41]:
data[2:1]

array([], dtype=int32)

In [43]:
data[2:]

array([33, 44, 55])

In [44]:
data[1:]

array([22, 33, 44, 55])

In [45]:
data[:1]

array([11])

In [47]:
data

array([11, 22, 33, 44, 55])

In [48]:
data[1:-2]

array([22, 33])

In [49]:
data[2:]

array([33, 44, 55])

In [51]:
data[-3:]

array([33, 44, 55])

In [52]:
data = array([[11, 22], [33, 44], [55, 66]])

In [53]:
data

array([[11, 22],
       [33, 44],
       [55, 66]])

In [54]:
data[:, :-1]

array([[11],
       [33],
       [55]])

In [56]:
data[:-1, :]

array([[11, 22],
       [33, 44]])

In [57]:
# training = data[:-100, :]
# test = data[-100:, :]

In [58]:
data = array([
    [11, 22, 33],
    [44, 55, 66],
    [77, 88, 99]
])

In [59]:
data

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [60]:
data[:, :-1]

array([[11, 22],
       [44, 55],
       [77, 88]])

In [61]:
data[:, -1:]

array([[33],
       [66],
       [99]])

In [ ]:
x = data[:, :-1]
y = data[:, -1:]

In [64]:
x, y = data[:, :-1], data[:, -1:]

In [ ]:
#df["col1"][:-10]
#df["col1"][-10:]

In [65]:
x

array([[11, 22],
       [44, 55],
       [77, 88]])

In [66]:
y

array([[33],
       [66],
       [99]])

In [71]:
data.shape

(3, 3)

In [72]:
x.shape

(3, 2)

In [73]:
y.shape

(3, 1)

In [67]:
data1 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

data2 = [
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
]

data3 = [data1, data2]

In [68]:
data3

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 20, 30], [40, 50, 60], [70, 80, 90]]]

In [75]:
#data3.shape

In [76]:
arr3d = array(data3)

In [78]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]])

In [79]:
arr3d.shape

(2, 3, 3)

In [84]:
arr3d[0, 0, :]

array([1, 2, 3])

In [85]:
arr3d[0, :, 0]

array([1, 4, 7])

In [86]:
arr3d[:, 0, 0]

array([ 1, 10])

In [87]:
arr3d[:, 0, :]

array([[ 1,  2,  3],
       [10, 20, 30]])

In [88]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]])

In [89]:
data = array([
    [11, 22, 33],
    [44, 55, 66],
    [77, 88, 99]
])

In [90]:
data = data[:-1, :]

In [91]:
data

array([[11, 22, 33],
       [44, 55, 66]])

In [92]:
data.shape

(2, 3)

In [93]:
data.reshape(3, 2)

array([[11, 22],
       [33, 44],
       [55, 66]])

In [94]:
data

array([[11, 22, 33],
       [44, 55, 66]])

In [95]:
data = data.reshape(3, 2)

In [96]:
data

array([[11, 22],
       [33, 44],
       [55, 66]])

In [97]:
data.reshape(2, 3)

array([[11, 22, 33],
       [44, 55, 66]])

In [98]:
data.reshape(6, 1)

array([[11],
       [22],
       [33],
       [44],
       [55],
       [66]])

In [100]:
#data.reshape(5, 1)

In [101]:
data

array([[11, 22],
       [33, 44],
       [55, 66]])

In [102]:
data.reshape(3, 2, 1)

array([[[11],
        [22]],

       [[33],
        [44]],

       [[55],
        [66]]])

In [103]:
data

array([[11, 22],
       [33, 44],
       [55, 66]])

In [106]:
# swaps rows and columns
data.transpose()

array([[11, 33, 55],
       [22, 44, 66]])

In [107]:
data.reshape(2, 3)

array([[11, 22, 33],
       [44, 55, 66]])

In [108]:
data

array([[11, 22],
       [33, 44],
       [55, 66]])

In [110]:
data.reshape(6, 1)

array([[11],
       [22],
       [33],
       [44],
       [55],
       [66]])

In [111]:
data.reshape(6, 1).shape

(6, 1)

In [114]:
data = data.reshape(6,)

In [115]:
data.shape

(6,)

In [116]:
data

array([11, 22, 33, 44, 55, 66])

In [117]:
data.shape[0]

6

In [118]:
data.reshape(data.shape[0],1)

array([[11],
       [22],
       [33],
       [44],
       [55],
       [66]])

In [119]:
data.reshape(1, data.shape[0])

array([[11, 22, 33, 44, 55, 66]])

In [120]:
data.reshape(1, data.shape[0], 1)

array([[[11],
        [22],
        [33],
        [44],
        [55],
        [66]]])

In [121]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]])

In [122]:
arr3d.shape

(2, 3, 3)

In [123]:
arr3d.shape[0]

2

In [124]:
arr3d.shape[1]

3

In [125]:
arr3d.shape[2]

3

In [126]:
data

array([11, 22, 33, 44, 55, 66])

reshape into an array with 3 rows and 2 columns

In [127]:
data.shape

(6,)

In [128]:
data = data.reshape(3, 2)

In [129]:
data.shape

(3, 2)

Reshape this 2d data array to a 3d array without using the numbers 2 or 3

shape = (3, 2, 1)

In [130]:
data = data.reshape(data.shape[0], data.shape[1], 1)

In [131]:
data.shape

(3, 2, 1)